-- Frozen compact5 decode baseline. Never derive older payloads from runtime defaults.
local ADDON_NAME, ST = ...
ST.COMPACT5_PROFILE_DEFAULTS = {
    ["auraTextureLibrary"] = {
        ["textureFavorites"] = {
        },
    },
    ["castBar"] = {
        ["backgroundColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0.5,
        },
        ["barColor"] = {
            [1] = 1,
            [2] = 0.7,
            [3] = 0,
            [4] = 1,
        },
        ["barTexture"] = "Solid",
        ["borderColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 1,
        },
        ["borderRenderMode"] = "custom",
        ["borderSize"] = 1,
        ["borderStyle"] = "pixel",
        ["castTimeFont"] = "Friz Quadrata TT",
        ["castTimeFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["castTimeFontOutline"] = "OUTLINE",
        ["castTimeFontSize"] = 10,
        ["castTimeXOffset"] = 0,
        ["castTimeYOffset"] = 0,
        ["enabled"] = false,
        ["height"] = 15,
        ["iconBorderRenderMode"] = "custom",
        ["iconBorderSize"] = 1,
        ["iconFlipSide"] = false,
        ["iconOffset"] = false,
        ["iconOffsetX"] = 0,
        ["iconOffsetY"] = 0,
        ["iconSize"] = 16,
        ["iconZoom"] = 0,
        ["independentAnchorEnabled"] = false,
        ["independentAnchorLocked"] = true,
        ["nameFont"] = "Friz Quadrata TT",
        ["nameFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["nameFontOutline"] = "OUTLINE",
        ["nameFontSize"] = 10,
        ["order"] = 2000,
        ["panelAnchorYOffset"] = 0,
        ["panelAnchorYOffsetEnabled"] = false,
        ["position"] = "below",
        ["showCastFinishFX"] = true,
        ["showCastTimeText"] = true,
        ["showIcon"] = true,
        ["showInterruptGlow"] = true,
        ["showInterruptShake"] = true,
        ["showNameText"] = true,
        ["showSpark"] = true,
        ["showSparkTrail"] = true,
    },
    ["escClosesConfig"] = true,
    ["frameAnchoring"] = {
        ["customPlayerFrame"] = "",
        ["customTargetFrame"] = "",
        ["enabled"] = false,
        ["inheritAlpha"] = true,
        ["mirroring"] = true,
        ["player"] = {
            ["anchorPoint"] = "RIGHT",
            ["relativePoint"] = "LEFT",
            ["xOffset"] = -10,
            ["yOffset"] = 0,
        },
        ["target"] = {
            ["anchorPoint"] = "LEFT",
            ["relativePoint"] = "RIGHT",
            ["xOffset"] = 10,
            ["yOffset"] = 0,
        },
    },
    ["globalStyle"] = {
        ["allowPings"] = false,
        ["assistedHighlightBlizzardOverhang"] = 32,
        ["assistedHighlightBorderSize"] = 2,
        ["assistedHighlightColor"] = {
            [1] = 0.3,
            [2] = 1,
            [3] = 0.3,
            [4] = 0.9,
        },
        ["assistedHighlightCombatOnly"] = false,
        ["assistedHighlightHostileTargetOnly"] = true,
        ["assistedHighlightProcColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["assistedHighlightProcOverhang"] = 32,
        ["assistedHighlightStyle"] = "blizzard",
        ["auraDurationSwipeAlpha"] = 0.8,
        ["auraDurationSwipeEdgeColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["auraDurationSwipeReverse"] = false,
        ["auraGlowColor"] = {
            [1] = 1,
            [2] = 0.84,
            [3] = 0,
            [4] = 0.9,
        },
        ["auraGlowColor2"] = {
            [1] = 0.1,
            [2] = 0.3,
            [3] = 1,
            [4] = 0.9,
        },
        ["auraGlowDashCount"] = 5,
        ["auraGlowDashThickness"] = 3,
        ["auraGlowLines"] = 8,
        ["auraGlowSize"] = 8,
        ["auraGlowSpeed"] = 50,
        ["auraGlowStyle"] = "pixel",
        ["auraGlowThickness"] = 4,
        ["auraKeepSpellCooldownSwipe"] = false,
        ["auraShowAuraIcon"] = false,
        ["auraTextAnchor"] = "TOPLEFT",
        ["auraTextXOffset"] = 2,
        ["auraTextYOffset"] = -2,
        ["auraUseBlizzardSwipe"] = false,
        ["barAuraColor"] = {
            [1] = 0.2,
            [2] = 1,
            [3] = 0.2,
            [4] = 1,
        },
        ["barAuraColorShiftColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["barAuraColorShiftEnabled"] = false,
        ["barAuraColorShiftSpeed"] = 0.5,
        ["barAuraEffect"] = "color",
        ["barAuraEffectColor"] = {
            [1] = 1,
            [2] = 0.84,
            [3] = 0,
            [4] = 0.9,
        },
        ["barAuraEffectLines"] = 8,
        ["barAuraEffectSize"] = 8,
        ["barAuraEffectSpeed"] = 50,
        ["barAuraEffectThickness"] = 4,
        ["barAuraPulseEnabled"] = false,
        ["barAuraPulseSpeed"] = 0.5,
        ["barBgColor"] = {
            [1] = 0.1,
            [2] = 0.1,
            [3] = 0.1,
            [4] = 0.8,
        },
        ["barChargeColor"] = {
            [1] = 1,
            [2] = 0.82,
            [3] = 0,
            [4] = 1,
        },
        ["barChargeSegmentGap"] = 4,
        ["barColor"] = {
            [1] = 0.2,
            [2] = 0.6,
            [3] = 1,
            [4] = 1,
        },
        ["barCooldownColor"] = {
            [1] = 0.6,
            [2] = 0.13,
            [3] = 0.18,
            [4] = 1,
        },
        ["barHeight"] = 20,
        ["barIconSize"] = 20,
        ["barIconSizeOverride"] = false,
        ["barLength"] = 180,
        ["barNameFont"] = "Friz Quadrata TT",
        ["barNameFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["barNameFontOutline"] = "OUTLINE",
        ["barNameFontSize"] = 10,
        ["barPandemicColor"] = {
            [1] = 1,
            [2] = 0.5,
            [3] = 0,
            [4] = 1,
        },
        ["barReadyFont"] = "Friz Quadrata TT",
        ["barReadyFontOutline"] = "OUTLINE",
        ["barReadyFontSize"] = 12,
        ["barReadyText"] = "Ready",
        ["barReadyTextColor"] = {
            [1] = 0.2,
            [2] = 1,
            [3] = 0.2,
            [4] = 1,
        },
        ["barSegmentCharges"] = false,
        ["barTexture"] = "Solid",
        ["borderColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 1,
        },
        ["borderRenderMode"] = "custom",
        ["borderSize"] = 1,
        ["buttonSize"] = 36,
        ["buttonSpacing"] = 2,
        ["chargeAnchor"] = "BOTTOMRIGHT",
        ["chargeFont"] = "Friz Quadrata TT",
        ["chargeFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["chargeFontColorMissing"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["chargeFontColorZero"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["chargeFontOutline"] = "OUTLINE",
        ["chargeFontSize"] = 12,
        ["chargeXOffset"] = -2,
        ["chargeYOffset"] = 2,
        ["cooldownFont"] = "Friz Quadrata TT",
        ["cooldownFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["cooldownFontOutline"] = "OUTLINE",
        ["cooldownFontSize"] = 12,
        ["cooldownPressFlashColor"] = {
            [1] = 1,
            [2] = 0.25,
            [3] = 0.25,
            [4] = 0.6,
        },
        ["cooldownPressFlashCombatOnly"] = false,
        ["cooldownPressFlashDuration"] = 0.25,
        ["cooldownPressFlashEnabled"] = false,
        ["cooldownSwipeAlpha"] = 0.8,
        ["cooldownSwipeEdgeColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["cooldownSwipeReverse"] = false,
        ["cooldownTextAnchor"] = "CENTER",
        ["cooldownTextXOffset"] = 0,
        ["cooldownTextYOffset"] = 0,
        ["desaturateOnCooldown"] = true,
        ["desaturateWhileAuraNotActive"] = false,
        ["durationFormat"] = "clock",
        ["iconAuraTintColor"] = {
            [1] = 0,
            [2] = 0.925,
            [3] = 1,
            [4] = 1,
        },
        ["iconAuraTintEnabled"] = false,
        ["iconCooldownTintColor"] = {
            [1] = 1,
            [2] = 0,
            [3] = 0.102,
            [4] = 1,
        },
        ["iconCooldownTintEnabled"] = false,
        ["iconFillCooldownColor"] = {
            [1] = 0.6,
            [2] = 0.13,
            [3] = 0.18,
            [4] = 0.55,
        },
        ["iconFillEnabled"] = false,
        ["iconFillOrientation"] = "vertical",
        ["iconFillReverse"] = false,
        ["iconFillTimerBehavior"] = "drain",
        ["iconTintColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["iconUnusableTintColor"] = {
            [1] = 0.4,
            [2] = 0.4,
            [3] = 0.4,
            [4] = 1,
        },
        ["iconWidthRatio"] = 1,
        ["invertAuraDesaturationLogic"] = false,
        ["keyPressHighlightColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 0.4,
        },
        ["keyPressHighlightCombatOnly"] = false,
        ["keyPressHighlightSize"] = 5,
        ["keyPressHighlightStyle"] = "none",
        ["keybindAnchor"] = "TOPRIGHT",
        ["keybindFont"] = "Friz Quadrata TT",
        ["keybindFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["keybindFontOutline"] = "OUTLINE",
        ["keybindFontSize"] = 10,
        ["keybindXOffset"] = -2,
        ["keybindYOffset"] = -2,
        ["maintainAspectRatio"] = true,
        ["missingAuraIndicatorEnabled"] = false,
        ["pandemicEffectEnabled"] = false,
        ["pandemicGlowColor"] = {
            [1] = 1,
            [2] = 0.5,
            [3] = 0,
            [4] = 1,
        },
        ["pandemicGlowColor2"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 0.9,
        },
        ["pandemicGlowLines"] = 8,
        ["pandemicGlowSize"] = 5,
        ["pandemicGlowSpeed"] = 50,
        ["pandemicGlowStyle"] = "solid",
        ["pandemicGlowThickness"] = 4,
        ["pandemicMarkerColor"] = {
            [1] = 1,
            [2] = 0.5,
            [3] = 0,
            [4] = 1,
        },
        ["pandemicMarkerColorMode"] = "marker",
        ["pandemicMarkerMode"] = "auto",
        ["pandemicMarkerText"] = "!!",
        ["procGlowColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["procGlowCombatOnly"] = false,
        ["procGlowLines"] = 8,
        ["procGlowOverhang"] = 32,
        ["procGlowSize"] = 30,
        ["procGlowSpeed"] = 50,
        ["procGlowStyle"] = "glow",
        ["procGlowThickness"] = 4,
        ["readyGlowColor"] = {
            [1] = 0.2,
            [2] = 1,
            [3] = 0.2,
            [4] = 1,
        },
        ["readyGlowCombatOnly"] = false,
        ["readyGlowDuration"] = 0,
        ["readyGlowLines"] = 8,
        ["readyGlowOnlyWhileUsable"] = false,
        ["readyGlowSize"] = 5,
        ["readyGlowSpeed"] = 50,
        ["readyGlowStyle"] = "none",
        ["readyGlowThickness"] = 4,
        ["separateTextPositions"] = false,
        ["showAssistedHighlight"] = false,
        ["showAuraDurationSwipe"] = true,
        ["showAuraDurationSwipeFill"] = true,
        ["showBarIcon"] = true,
        ["showBarNameText"] = true,
        ["showBarReadyText"] = false,
        ["showChargeText"] = true,
        ["showCooldownSwipe"] = true,
        ["showCooldownSwipeFill"] = true,
        ["showGCDSwipe"] = false,
        ["showKeybindText"] = false,
        ["showLossOfControl"] = true,
        ["showOutOfRange"] = true,
        ["showTextGroupHeader"] = false,
        ["showTooltips"] = false,
        ["showUnusable"] = true,
        ["textAlignment"] = "LEFT",
        ["textAuraColor"] = {
            [1] = 0,
            [2] = 0.925,
            [3] = 1,
            [4] = 1,
        },
        ["textBgColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0,
        },
        ["textBorderColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 1,
        },
        ["textBorderRenderMode"] = "custom",
        ["textBorderSize"] = 0,
        ["textCooldownColor"] = {
            [1] = 1,
            [2] = 0.3,
            [3] = 0.3,
            [4] = 1,
        },
        ["textCustomColor"] = {
            [1] = 1,
            [2] = 0.82,
            [3] = 0,
            [4] = 1,
        },
        ["textFont"] = "Friz Quadrata TT",
        ["textFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["textFontOutline"] = "OUTLINE",
        ["textFontSize"] = 12,
        ["textFormat"] = "{name}  {status}",
        ["textHeaderFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["textHeaderFontSize"] = 12,
        ["textPadding"] = 4,
        ["textReadyColor"] = {
            [1] = 0.2,
            [2] = 1,
            [3] = 0.2,
            [4] = 1,
        },
        ["textReadyText"] = "Ready",
        ["textShadow"] = false,
        ["textureIndicators"] = {
            ["aura"] = {
                ["color"] = {
                    [1] = 1,
                    [2] = 0.84,
                    [3] = 0,
                    [4] = 1,
                },
                ["combatOnly"] = false,
                ["effectType"] = "colorShift",
                ["enabled"] = false,
                ["invert"] = false,
                ["speed"] = 0.5,
            },
            ["proc"] = {
                ["color"] = {
                    [1] = 1,
                    [2] = 1,
                    [3] = 1,
                    [4] = 1,
                },
                ["combatOnly"] = false,
                ["effectType"] = "pulse",
                ["enabled"] = false,
                ["speed"] = 0.5,
            },
            ["ready"] = {
                ["color"] = {
                    [1] = 0.2,
                    [2] = 1,
                    [3] = 0.2,
                    [4] = 1,
                },
                ["combatOnly"] = false,
                ["effectType"] = "bounce",
                ["enabled"] = false,
                ["speed"] = 0.5,
            },
            ["unusable"] = {
                ["color"] = {
                    [1] = 1,
                    [2] = 0.35,
                    [3] = 0.35,
                    [4] = 1,
                },
                ["combatOnly"] = false,
                ["effectType"] = "pulse",
                ["enabled"] = false,
                ["speed"] = 0.5,
            },
        },
        ["tooltipAnchor"] = "default",
        ["tooltipHideInCombat"] = false,
        ["unusableVisualMode"] = "dim",
    },
    ["groupSettingPresets"] = {
        ["bars"] = {
        },
        ["icons"] = {
        },
    },
    ["locked"] = false,
    ["minimap"] = {
        ["hide"] = false,
    },
    ["profileWideBarTextureEnabled"] = false,
    ["profileWideFontEnabled"] = false,
    ["resourceBarMigration"] = {
        ["conflicts"] = {
        },
        ["unsafeCharKeys"] = {
        },
    },
    ["resourceBars"] = {
        ["backgroundColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 0.5,
        },
        ["barHeight"] = 12,
        ["barSpacing"] = 3.6,
        ["barTexture"] = "Solid",
        ["barWidth"] = 12,
        ["baselineAlpha"] = 1,
        ["borderColor"] = {
            [1] = 0,
            [2] = 0,
            [3] = 0,
            [4] = 1,
        },
        ["borderRenderMode"] = "custom",
        ["borderSize"] = 1,
        ["borderStyle"] = "pixel",
        ["customAuraBarSlots"] = {
            [1] = {
                ["order"] = 1001,
                ["position"] = "below",
            },
            [2] = {
                ["order"] = 1002,
                ["position"] = "below",
            },
            [3] = {
                ["order"] = 1003,
                ["position"] = "below",
            },
            [4] = {
                ["order"] = 1004,
                ["position"] = "below",
            },
            [5] = {
                ["order"] = 1005,
                ["position"] = "below",
            },
        },
        ["customAuraBars"] = {
        },
        ["customBars"] = {
        },
        ["customFade"] = false,
        ["displayProfiles"] = {
        },
        ["enabled"] = false,
        ["fadeDelay"] = 1,
        ["fadeInDuration"] = 0.2,
        ["fadeOutDuration"] = 0.2,
        ["forceAlphaDragonriding"] = false,
        ["forceAlphaFocusExists"] = false,
        ["forceAlphaInCombat"] = false,
        ["forceAlphaMouseover"] = false,
        ["forceAlphaOutOfCombat"] = false,
        ["forceAlphaRegularMounted"] = false,
        ["forceAlphaTargetEnemyOnly"] = false,
        ["forceAlphaTargetExists"] = false,
        ["forceHideDragonriding"] = false,
        ["forceHideInCombat"] = false,
        ["forceHideOutOfCombat"] = false,
        ["forceHideRegularMounted"] = false,
        ["hideManaForNonHealer"] = true,
        ["independentAnchorEnabled"] = false,
        ["independentAnchorLocked"] = true,
        ["inheritAlpha"] = false,
        ["layoutOrder"] = {
        },
        ["nextCustomBarId"] = 1,
        ["orientation"] = "horizontal",
        ["resources"] = {
            [-1] = {
                ["enabled"] = false,
                ["healthAbsorbColor"] = {
                    [1] = 0.55,
                    [2] = 0.85,
                    [3] = 1,
                    [4] = 0.45,
                },
                ["healthAbsorbTexture"] = "Solid",
                ["healthBackgroundGradient"] = true,
                ["healthBackgroundOpacity"] = 1,
                ["healthBarGradient"] = false,
                ["healthBarOpacity"] = 0.7,
                ["healthHealAbsorbColor"] = {
                    [1] = 1,
                    [2] = 0.12,
                    [3] = 0.12,
                    [4] = 0.55,
                },
                ["healthHealAbsorbTexture"] = "Solid",
                ["healthIncomingHealColor"] = {
                    [1] = 0.1,
                    [2] = 0.85,
                    [3] = 0.35,
                    [4] = 0.45,
                },
                ["healthIncomingHealTexture"] = "Solid",
                ["healthLowHealthAlertColor"] = {
                    [1] = 1,
                    [2] = 0.08,
                    [3] = 0.04,
                    [4] = 0.35,
                },
                ["healthLowHealthAlertMissingHealthOnly"] = false,
                ["healthLowHealthAlertTexture"] = "Solid",
                ["showAbsorbs"] = true,
                ["showHealAbsorbs"] = true,
                ["showIncomingHeals"] = true,
                ["showLowHealthAlert"] = false,
                ["showText"] = false,
                ["textFormat"] = "percent",
            },
            [100] = {
                ["continuousTickAbsolute"] = 50,
                ["continuousTickCombatOnly"] = false,
                ["continuousTickEnabled"] = false,
                ["continuousTickMode"] = "percent",
                ["continuousTickPercent"] = 50,
                ["enabled"] = true,
                ["segThresholdEnabled"] = false,
                ["segThresholdValue"] = 1,
            },
            [101] = {
                ["enabled"] = true,
                ["showText"] = false,
                ["textFormat"] = "percent",
            },
        },
        ["segmentGap"] = 4,
        ["segmentedSmoothing"] = "on",
        ["textFont"] = "Friz Quadrata TT",
        ["textFontColor"] = {
            [1] = 1,
            [2] = 1,
            [3] = 1,
            [4] = 1,
        },
        ["textFontOutline"] = "OUTLINE",
        ["textFontSize"] = 10,
        ["textFormat"] = "current",
        ["treatTravelFormAsMounted"] = false,
        ["verticalFillDirection"] = "bottom_to_top",
        ["verticalXOffset"] = 3,
        ["yOffset"] = 3,
    },
    ["showAdvanced"] = {
    },
}
ST.COMPACT5_ENTITY_DEFAULTS = {
    ["container"] = {
        ["baselineAlpha"] = 1,
        ["enabled"] = true,
        ["fadeDelay"] = 1,
        ["fadeInDuration"] = 0.2,
        ["fadeOutDuration"] = 0.2,
        ["forceAlphaDragonriding"] = false,
        ["forceAlphaFocusExists"] = false,
        ["forceAlphaInCombat"] = false,
        ["forceAlphaMouseover"] = false,
        ["forceAlphaOutOfCombat"] = false,
        ["forceAlphaRegularMounted"] = false,
        ["forceAlphaTargetEnemyOnly"] = false,
        ["forceAlphaTargetExists"] = false,
        ["forceHideDragonriding"] = false,
        ["forceHideInCombat"] = false,
        ["forceHideOutOfCombat"] = false,
        ["forceHideRegularMounted"] = false,
        ["groupAlphaEnabled"] = false,
        ["locked"] = true,
        ["treatTravelFormAsMounted"] = false,
    },
    ["containerAnchor"] = {
        ["point"] = "CENTER",
        ["relativePoint"] = "CENTER",
        ["relativeTo"] = "UIParent",
        ["x"] = 0,
        ["y"] = 0,
    },
    ["loadConditions"] = {
        ["arena"] = false,
        ["battleground"] = false,
        ["delve"] = false,
        ["dungeon"] = false,
        ["openWorld"] = false,
        ["petBattle"] = true,
        ["raid"] = false,
        ["rested"] = false,
        ["vehicleUI"] = true,
    },
    ["panel"] = {
        ["baselineAlpha"] = 1,
        ["compactGrowthDirection"] = "center",
        ["compactLayout"] = true,
        ["displayMode"] = "icons",
        ["fadeDelay"] = 1,
        ["fadeInDuration"] = 0.2,
        ["fadeOutDuration"] = 0.2,
        ["forceAlphaFocusExists"] = false,
        ["forceAlphaTargetEnemyOnly"] = false,
        ["inheritPanelAlpha"] = true,
        ["masqueEnabled"] = false,
        ["maxVisibleButtons"] = 0,
    },
}
